In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt


In [2]:
train = pd.read_csv(r"C:\Users\91892\Downloads\emnist-letters-train.csv",header=None)
test = pd.read_csv(r"C:\Users\91892\Downloads\emnist-letters-test.csv",header=None)

In [3]:
train 

0    1    2    3    4    5    6    7    8    9    ...  775  776  777  \
0       23    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1        7    0    0    0    0    0    0    0    0    0  ...    0    0    0   
2       16    0    0    0    0    0    0    0    0    0  ...    0    0    0   
3       15    0    0    0    0    0    0    0    0    0  ...    0    0    0   
4       23    0    0    0    0    0    0    0    0    0  ...    0    0    0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
88795    1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
88796   21    0    0    0    0    0    0    0    0    0  ...    0    0    0   
88797    1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
88798   23    0    0    0    0    0    0    0    0    0  ...    0    0    0   
88799   12    0    0    0    0    0    0    0    0    0  ...    0    0    0   

       778  779  780  781  782  783  784  
0        0    0    0    0    0    0    0  
1        0    0    0    0    0    0    0  
2        0    0    0    0    0    0    0  
3        0    0    0    0    0    0    0  
4        0    0    0    0    0    0    0  
...    ...  ...  ...  ...  ...  ...  ...  
88795    0    0    0    0    0    0    0  
88796    0    0    0    0    0    0    0  
88797    0    0    0    0    0    0    0  
88798    0    0    0    0    0    0    0  
88799    0    0    0    0    0    0    0  

[88800 rows x 785 columns]

In [4]:
test

0    1    2    3    4    5    6    7    8    9    ...  775  776  777  \
0        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
2        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
3        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
4        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
14795   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14796   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14797   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14798   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14799   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   

       778  779  780  781  782  783  784  
0        0    0    0    0    0    0    0  
1        0    0    0    0    0    0    0  
2        0    0    0    0    0    0    0  
3        0    0    0    0    0    0    0  
4        0    0    0    0    0    0    0  
...    ...  ...  ...  ...  ...  ...  ...  
14795    0    0    0    0    0    0    0  
14796    0    0    0    0    0    0    0  
14797    0    0    0    0    0    0    0  
14798    0    0    0    0    0    0    0  
14799    0    0    0    0    0    0    0  

[14800 rows x 785 columns]

In [5]:
training_data = train.values
testing_data = test.values
X_test = testing_data[:, 1:]/255
Y_test = testing_data[:, 0].reshape(testing_data.shape[0],1)
X_train = training_data[:, 1:]/255
Y_train = training_data[:, 0].reshape(training_data.shape[0],1)
print("The shape of X_train is", X_train.shape)
print("The shape of X_test is", X_test.shape)
print("The shape of Y_train is", Y_train.shape)
print("The shape of Y_test is", Y_test.shape)

The shape of X_train is (88800, 784)
The shape of X_test is (14800, 784)
The shape of Y_train is (88800, 1)
The shape of Y_test is (14800, 1)


In [6]:
m,n = X_train.shape


In [7]:
rand  = np.random.randint(1, m, 26)
rand


array([24934, 52290, 25066, 76326, 70156, 83199, 54951, 43215, 34875,
       20955, 55102, 30527, 51561,  3552, 14293, 68277, 78919, 77943,
       54289, 18858, 26790, 88584, 30466, 72008, 76416, 36352])

In [8]:
centroid = []
for i in rand:
    centroid.append(X_train[i])
centroid = np.array(centroid)  

In [9]:
answers = []
for j in range(88800):
    diff = (centroid - X_train[j])**2
    sume = np.sum(diff, axis = 1)
    distance = np.sqrt(sume)
    index = np.argmin(distance)
    answers.append(index + 1)

In [10]:
answers = np.array(answers)
answers

array([16, 21,  3, ...,  9, 19, 11], dtype=int64)

In [11]:
cluster_1 = X_train[answers == 1]
n_centroid_1 = np.mean(cluster_1, axis = 0)
n_centroid_1

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 1.87994661e-06, 3.75989322e-05, 4.88786118e-05,
       9.21173839e-05, 1.33476209e-04, 1.24076476e-04, 6.01582915e-05,
       4.32387720e-05, 3.94788788e-05, 4.51187186e-05, 1.56035569e-04,
       3.47790123e-04, 5.13225424e-04, 6.05342808e-04, 6.61741207e-04,
       7.01220085e-04, 7.70778110e-04, 7.68898163e-04, 5.16985318e-04,
       5.07585585e-04, 2.55672739e-04, 1.87994661e-04, 1.22196530e-04,
       3.00791458e-05, 1.87994661e-06, 0.00000000e+00, 0.00000000e+00,
      

In [12]:
n_centroid=[]
for k in range(1,27):
    cluster_xyz=X_train[answers==k]
    avg_cluster=np.mean(cluster_xyz,axis=0)
    n_centroid.append(avg_cluster)
n_centroid=np.array(n_centroid)


In [13]:
n_centroid[0]

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 1.87994661e-06, 3.75989322e-05, 4.88786118e-05,
       9.21173839e-05, 1.33476209e-04, 1.24076476e-04, 6.01582915e-05,
       4.32387720e-05, 3.94788788e-05, 4.51187186e-05, 1.56035569e-04,
       3.47790123e-04, 5.13225424e-04, 6.05342808e-04, 6.61741207e-04,
       7.01220085e-04, 7.70778110e-04, 7.68898163e-04, 5.16985318e-04,
       5.07585585e-04, 2.55672739e-04, 1.87994661e-04, 1.22196530e-04,
       3.00791458e-05, 1.87994661e-06, 0.00000000e+00, 0.00000000e+00,
      

In [17]:
for l in range(100):
    answers_sho = np.zeros((88800,1))
    for m in range(88800):
        distance_sho = np.sqrt(np.sum(((n_centroid - X_train[m])**2), axis = 0))
        index_sho = np.argmin(distance_sho)
        index_sho=int(index_sho)
        answers_sho[m]=((index_sho + 1))
        
    answers_sho= np.array(answers_sho)

    n_centroid_sho=np.zeros((26,784))
    for n in range(1,27):
        shobhi=answer_sho=n
    
        cluster_xyz_sho=X_train[shobhi]
        avg_cluster_sho=np.mean(cluster_xyz_sho,axis=0)
        n_centroid_sho[n-1]=(avg_cluster_sho)

    

In [18]:
answers_sho = []
for o in range(88800):
    diff_sho = (n_centroid_sho - X_train[o])**2
    sume_sho = np.sum(diff_sho, axis = 1)
    distance_sho = np.sqrt(sume_sho)
    index_sho = np.argmin(distance_sho)
    answers_sho.append(index_sho + 1)

In [19]:
answers_sho

[1,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 3,
 7,
 4,
 8,
 22,
 19,
 15,
 5,
 4,
 17,
 20,
 25,
 8,
 6,
 16,
 9,
 5,
 4,
 22,
 13,
 5,
 13,
 8,
 19,
 15,
 11,
 1,
 24,
 25,
 24,
 22,
 24,
 11,
 17,
 9,
 20,
 8,
 19,
 22,
 14,
 16,
 19,
 5,
 19,
 15,
 16,
 11,
 3,
 9,
 9,
 4,
 3,
 13,
 22,
 8,
 23,
 22,
 25,
 24,
 22,
 19,
 14,
 11,
 25,
 24,
 8,
 15,
 16,
 9,
 10,
 22,
 22,
 8,
 18,
 10,
 11,
 22,
 4,
 21,
 26,
 11,
 11,
 18,
 5,
 24,
 16,
 12,
 8,
 9,
 4,
 4,
 19,
 16,
 19,
 11,
 3,
 1,
 8,
 24,
 16,
 8,
 16,
 11,
 8,
 15,
 19,
 8,
 11,
 25,
 22,
 22,
 5,
 7,
 5,
 23,
 17,
 9,
 23,
 11,
 18,
 9,
 22,
 13,
 25,
 22,
 19,
 7,
 11,
 4,
 3,
 13,
 8,
 8,
 23,
 16,
 8,
 18,
 5,
 14,
 9,
 8,
 22,
 15,
 13,
 6,
 6,
 11,
 5,
 5,
 15,
 19,
 9,
 17,
 8,
 19,
 17,
 18,
 8,
 25,
 8,
 5,
 8,
 11,
 19,
 4,
 9,
 22,
 8,
 11,
 19,
 7,
 8,
 15,
 22,
 24,
 19,
 24,
 11,
 23,
 24,
 15,
 24,
 3,
 8,
 19,
 8,
 22,
 8,
 4,
 4